export type MediaType = 'movie' | 'series';
export type MediaStatus = 'planned' | 'watching' | 'suspended' | 'completed' | 'reviewed';

export interface MediaItem {
  id: string;
  title: string;
  type: MediaType;
  status: MediaStatus;
  rating?: number;
  categories: string[];
  notes?: string;
  poster: string;
  releaseYear?: number;
  totalSeasons?: number;
  totalEpisodes?: number;
  currentSeason?: number;
  currentEpisode?: number;
  dateAdded: Date;
}

export const categories = [
  'Action',
  'Comedy',
  'Drama',
  'Fantasy',
  'Horror',
  'Romance',
  'Sci-Fi',
  'Thriller',
  'Animation',
  'Documentary',
];

export const mockMedia: MediaItem[] = [
  {
    id: '1',
    title: 'Dune: Part Two',
    type: 'movie',
    status: 'completed',
    rating: 9,
    categories: ['Sci-Fi', 'Action'],
    poster: 'https://images.unsplash.com/photo-1533100235316-f6c4da8e89f1?w=300&h=450&fit=crop',
    releaseYear: 2024,
    notes: 'Absolutely stunning visuals and cinematography. A masterpiece!',
    dateAdded: new Date('2024-02-15'),
  },
  {
    id: '2',
    title: 'Breaking Bad',
    type: 'series',
    status: 'completed',
    rating: 10,
    categories: ['Drama', 'Thriller'],
    poster: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=300&h=450&fit=crop',
    releaseYear: 2008,
    totalSeasons: 5,
    totalEpisodes: 62,
    currentSeason: 5,
    currentEpisode: 16,
    notes: 'One of the best TV shows ever made. Incredible character development.',
    dateAdded: new Date('2024-01-10'),
  },
  {
    id: '3',
    title: 'Oppenheimer',
    type: 'movie',
    status: 'completed',
    rating: 8.5,
    categories: ['Drama', 'History'],
    poster: 'https://images.unsplash.com/photo-1566875565535-33a57e5c5fe0?w=300&h=450&fit=crop',
    releaseYear: 2023,
    notes: 'Brilliant direction by Nolan. A very intense and thought-provoking film.',
    dateAdded: new Date('2024-03-01'),
  },
  {
    id: '4',
    title: 'Stranger Things',
    type: 'series',
    status: 'completed',
    rating: 8,
    categories: ['Sci-Fi', 'Horror', 'Drama'],
    poster: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=300&h=450&fit=crop',
    releaseYear: 2016,
    totalSeasons: 4,
    totalEpisodes: 42,
    currentSeason: 4,
    currentEpisode: 9,
    notes: 'Great 80s nostalgia. The final season was a bit rushed.',
    dateAdded: new Date('2023-11-20'),
  },
  {
    id: '5',
    title: 'Killers of the Flower Moon',
    type: 'movie',
    status: 'completed',
    rating: 8.5,
    categories: ['Drama', 'Crime'],
    poster: 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?w=300&h=450&fit=crop',
    releaseYear: 2023,
    notes: 'Scorsese continues to make exceptional films. Outstanding performances.',
    dateAdded: new Date('2024-02-20'),
  },
  {
    id: '6',
    title: 'Succession',
    type: 'series',
    status: 'completed',
    rating: 9.5,
    categories: ['Drama', 'Thriller'],
    poster: 'https://images.unsplash.com/photo-1557804506-669714d2e745?w=300&h=450&fit=crop',
    releaseYear: 2018,
    totalSeasons: 4,
    totalEpisodes: 39,
    currentSeason: 4,
    currentEpisode: 9,
    notes: 'Incredible storytelling and character arcs. The finale was perfect.',
    dateAdded: new Date('2024-01-05'),
  },
  {
    id: '7',
    title: 'Barbie',
    type: 'movie',
    status: 'completed',
    rating: 8,
    categories: ['Comedy', 'Fantasy'],
    poster: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=300&h=450&fit=crop',
    releaseYear: 2023,
    notes: 'Fun, colorful, and surprisingly clever. Great entertainment.',
    dateAdded: new Date('2023-08-10'),
  },
  {
    id: '8',
    title: 'The Last of Us',
    type: 'series',
    status: 'watching',
    rating: 9,
    categories: ['Drama', 'Action', 'Sci-Fi'],
    poster: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=300&h=450&fit=crop',
    releaseYear: 2023,
    totalSeasons: 1,
    totalEpisodes: 9,
    currentSeason: 1,
    currentEpisode: 5,
    notes: 'Gripping adaptation of the game. Incredible performances.',
    dateAdded: new Date('2024-03-15'),
  },
  {
    id: '9',
    title: 'Past Lives',
    type: 'movie',
    status: 'planned',
    categories: ['Romance', 'Drama'],
    poster: 'https://images.unsplash.com/photo-1566875565535-33a57e5c5fe0?w=300&h=450&fit=crop',
    releaseYear: 2023,
    notes: 'Heard great reviews. Want to watch soon.',
    dateAdded: new Date('2024-03-20'),
  },
  {
    id: '10',
    title: 'The Bear',
    type: 'series',
    status: 'watching',
    rating: 8.5,
    categories: ['Drama', 'Comedy'],
    poster: 'https://images.unsplash.com/photo-1557804506-669714d2e745?w=300&h=450&fit=crop',
    releaseYear: 2022,
    totalSeasons: 2,
    totalEpisodes: 16,
    currentSeason: 2,
    currentEpisode: 8,
    notes: 'Intense kitchen drama. Excellent writing and acting.',
    dateAdded: new Date('2024-03-01'),
  },
  {
    id: '11',
    title: 'American Beauty',
    type: 'movie',
    status: 'completed',
    rating: 8,
    categories: ['Drama'],
    poster: 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?w=300&h=450&fit=crop',
    releaseYear: 1999,
    notes: 'A classic that still holds up. Haunting and beautiful.',
    dateAdded: new Date('2023-12-05'),
  },
  {
    id: '12',
    title: 'Fallout',
    type: 'series',
    status: 'planned',
    categories: ['Sci-Fi', 'Action', 'Drama'],
    poster: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=300&h=450&fit=crop',
    releaseYear: 2024,
    totalSeasons: 1,
    totalEpisodes: 8,
    notes: 'Adaptation of the video game series. Looking forward to it!',
    dateAdded: new Date('2024-03-25'),
  },
];
